### ISSUE TITLE
Invalid Host on Updater tool

### ISSUE THREAD

**Issue by M-Davies** [AdoptOpenJDK/openjdk-api-v3#298]
**Describe the bug**
I have been trying to replicate the Adopt API Locally using the instructions in `contributing.md` and `structure.md` and have hit this error both in the artifact generator (`mvnw clean install`) and the updater tool (`java -jar ./target/adoptopenjdk-api-v3-updater-3.0.0-SNAPSHOT-jar-with-dependencies.jar`), except the error doesn't cause the artifact generator to fail.

**To Reproduce**
1. Clone this repo.
2. Install Java 11, my version is 
```
openjdk 11.0.8 2020-07-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.8+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.8+10, mixed mode)
```
3. Created a GitHub PAC Token with the public repo permission enabled.
4. Followed the recommended guide to install mongo in `contributing.md`. I also did `brew install maven` at this point (even though I'm fairly sure it's not needed)
5. `./mvnw clean install`. This produced the error in the console log a few times but didn't fail the build:
```java
[INFO] Running net.adoptopenjdk.api.ReleaseNamesPathTest
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/Users/morgan/.m2/repository/org/jboss/slf4j/slf4j-jboss-logging/1.2.0.Final/slf4j-jboss-logging-1.2.0.Final.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/Users/morgan/.m2/repository/ch/qos/logback/logback-classic/1.2.3/logback-classic-1.2.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.jboss.slf4j.JBossLoggerFactory]
2020-11-04 11:11:59,724 WARN  [io.qua.dep.ste.ReflectiveHierarchyStep] (build-8) Unable to properly register the hierarchy of the following classes for reflection as they are not in the Jandex index:
	- org.bson.Document (source: net.adoptopenjdk.api.v3.routes.stats.DownloadStatsResource)
	- org.litote.kmongo.coroutine.CoroutineClient (source: net.adoptopenjdk.api.v3.routes.stats.DownloadStatsResource)
	- org.litote.kmongo.coroutine.CoroutineCollection (source: net.adoptopenjdk.api.v3.routes.stats.DownloadStatsResource)
	- org.litote.kmongo.coroutine.CoroutineDatabase (source: net.adoptopenjdk.api.v3.routes.stats.DownloadStatsResource)
Consider adding them to the index either by creating a Jandex index for your dependency via the Maven plugin, an empty META-INF/beans.xml or quarkus.index-dependency properties.");.
2020-11-04 11:12:02,404 INFO  [net.ado.api.v3.dat.per.mon.MongoClient$Companion] (main) Using development connection string - mongodb://null:null/?serverSelectionTimeoutMS=null
2020-11-04 11:12:02,415 ERROR [net.ado.api.v3.dat.APIDataStore] (main) Failed to read db: java.lang.IllegalArgumentException: The connection string contains an invalid host 'null:null'. The port 'null' is not a valid, it must be an integer between 0 and 65535
	at com.mongodb.ConnectionString.validatePort(ConnectionString.java:1003)
	at com.mongodb.ConnectionString.parseHosts(ConnectionString.java:983)
	at com.mongodb.ConnectionString.<init>(ConnectionString.java:340)
	at org.litote.kmongo.reactivestreams.KMongo.createClient(KMongo.kt:57)
	at net.adoptopenjdk.api.v3.dataSources.persitence.mongo.MongoClient.<init>(MongoClient.kt:68)
	at net.adoptopenjdk.api.v3.dataSources.persitence.mongo.MongoClientFactory.get(MongoClient.kt:15)
	at net.adoptopenjdk.api.v3.dataSources.ApiPersistenceFactory.get(ApiPersistenceFactory.kt:13)
	at net.adoptopenjdk.api.v3.dataSources.APIDataStore$loadDataFromDb$1.invokeSuspend(APIDataStore.kt:87)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:272)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:79)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:54)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:36)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at net.adoptopenjdk.api.v3.dataSources.APIDataStore.loadDataFromDb(APIDataStore.kt:86)
	at net.adoptopenjdk.api.v3.dataSources.APIDataStore.<clinit>(APIDataStore.kt:38)
	at net.adoptopenjdk.api.v3.V3.<init>(V3.kt:59)
	at net.adoptopenjdk.api.v3.V3_Bean.create(V3_Bean.zig:139)
	at net.adoptopenjdk.api.v3.V3_Bean.create(V3_Bean.zig:154)
	at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:88)
	at io.quarkus.arc.impl.ComputingCache$CacheFunction.lambda$apply$0(ComputingCache.java:99)
	at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:26)
	at io.quarkus.arc.impl.ComputingCache.getValue(ComputingCache.java:41)
	at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:25)
	at net.adoptopenjdk.api.v3.V3_Bean.get(V3_Bean.zig:186)
	at net.adoptopenjdk.api.v3.V3_Bean.get(V3_Bean.zig:202)
	at io.quarkus.arc.impl.ArcContainerImpl.beanInstanceHandle(ArcContainerImpl.java:408)
	at io.quarkus.arc.impl.ArcContainerImpl.beanInstanceHandle(ArcContainerImpl.java:421)
	at io.quarkus.arc.impl.ArcContainerImpl$1.get(ArcContainerImpl.java:249)
	at io.quarkus.arc.impl.ArcContainerImpl$1.get(ArcContainerImpl.java:246)
	at io.quarkus.arc.runtime.ArcRecorder$2$1.create(ArcRecorder.java:84)
	at io.quarkus.resteasy.common.runtime.QuarkusConstructorInjector.construct(QuarkusConstructorInjector.java:39)
	at org.jboss.resteasy.core.providerfactory.Utils.createProviderInstance(Utils.java:102)
	at org.jboss.resteasy.core.providerfactory.ResteasyProviderFactoryImpl.createProviderInstance(ResteasyProviderFactoryImpl.java:1384)
```
and again later on...
```java
2020-11-04 11:12:02,426 INFO  [net.ado.api.v3.dat.per.mon.MongoClient$Companion] (main) Using development connection string - mongodb://null:null/?serverSelectionTimeoutMS=null
2020-11-04 11:12:02,426 ERROR [net.ado.api.v3.dat.APIDataStore] (main) Failed to read db: java.lang.IllegalArgumentException: The connection string contains an invalid host 'null:null'. The port 'null' is not a valid, it must be an integer between 0 and 65535
	at com.mongodb.ConnectionString.validatePort(ConnectionString.java:1003)
	at com.mongodb.ConnectionString.parseHosts(ConnectionString.java:983)
	at com.mongodb.ConnectionString.<init>(ConnectionString.java:340)
	at org.litote.kmongo.reactivestreams.KMongo.createClient(KMongo.kt:57)
	at net.adoptopenjdk.api.v3.dataSources.persitence.mongo.MongoClient.<init>(MongoClient.kt:68)
	at net.adoptopenjdk.api.v3.dataSources.persitence.mongo.MongoClientFactory.get(MongoClient.kt:15)
	at net.adoptopenjdk.api.v3.dataSources.ApiPersistenceFactory.get(ApiPersistenceFactory.kt:13)
	at net.adoptopenjdk.api.v3.dataSources.APIDataStore$loadReleaseInfo$1.invokeSuspend(APIDataStore.kt:63)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:272)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:79)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:54)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:36)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at net.adoptopenjdk.api.v3.dataSources.APIDataStore.loadReleaseInfo(APIDataStore.kt:61)
	at net.adoptopenjdk.api.v3.dataSources.APIDataStore.<clinit>(APIDataStore.kt:44)
	at net.adoptopenjdk.api.v3.V3.<init>(V3.kt:59)
	at net.adoptopenjdk.api.v3.V3_Bean.create(V3_Bean.zig:139)
	at net.adoptopenjdk.api.v3.V3_Bean.create(V3_Bean.zig:154)
	at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:88)
	at io.quarkus.arc.impl.ComputingCache$CacheFunction.lambda$apply$0(ComputingCache.java:99)
	at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:26)
	at io.quarkus.arc.impl.ComputingCache.getValue(ComputingCache.java:41)
	at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:25)
	at net.adoptopenjdk.api.v3.V3_Bean.get(V3_Bean.zig:186)
	at net.adoptopenjdk.api.v3.V3_Bean.get(V3_Bean.zig:202)
	at io.quarkus.arc.impl.ArcContainerImpl.beanInstanceHandle(ArcContainerImpl.java:408)
	at io.quarkus.arc.impl.ArcContainerImpl.beanInstanceHandle(ArcContainerImpl.java:421)
	at io.quarkus.arc.impl.ArcContainerImpl$1.get(ArcContainerImpl.java:249)
	at io.quarkus.arc.impl.ArcContainerImpl$1.get(ArcContainerImpl.java:246)
	at io.quarkus.arc.runtime.ArcRecorder$2$1.create(ArcRecorder.java:84)
	at io.quarkus.resteasy.common.runtime.QuarkusConstructorInjector.construct(QuarkusConstructorInjector.java:39)
	at org.jboss.resteasy.core.providerfactory.Utils.createProviderInstance(Utils.java:102)
	at org.jboss.resteasy.core.providerfactory.ResteasyProviderFactoryImpl.createProviderInstance(ResteasyProviderFactoryImpl.java:1384)
	at org.jboss.resteasy.core.ResteasyDeploymentImpl.createApplication(ResteasyDeploymentImpl.java:415)
	at org.jboss.resteasy.core.ResteasyDeploymentImpl.initializeObjects(ResteasyDeploymentImpl.java:262)
	at org.jboss.resteasy.core.ResteasyDeploymentImpl.startInternal(ResteasyDeploymentImpl.java:135)
	at org.jboss.resteasy.core.ResteasyDeploymentImpl.start(ResteasyDeploymentImpl.java:118)
	at io.quarkus.resteasy.runtime.standalone.ResteasyStandaloneRecorder.staticInit(ResteasyStandaloneRecorder.java:86)
	at io.quarkus.deployment.steps.ResteasyStandaloneBuildStep$staticInit-210558872.deploy_0(ResteasyStandaloneBuildStep$staticInit-210558872.zig:1159)
	at io.quarkus.deployment.steps.ResteasyStandaloneBuildStep$staticInit-210558872.deploy(ResteasyStandaloneBuildStep$staticInit-210558872.zig:36)
	at io.quarkus.runner.ApplicationImpl.<clinit>(ApplicationImpl.zig:165)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:398)
	at io.quarkus.runner.bootstrap.StartupActionImpl.run(StartupActionImpl.java:207)
	at io.quarkus.test.junit.QuarkusTestExtension.doJavaStart(QuarkusTestExtension.java:198)
	at io.quarkus.test.junit.QuarkusTestExtension.ensureStarted(QuarkusTestExtension.java:406)
	at io.quarkus.test.junit.QuarkusTestExtension.beforeAll(QuarkusTestExtension.java:439)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$invokeBeforeAllCallbacks$7(ClassBasedTestDescriptor.java:359)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeBeforeAllCallbacks(ClassBasedTestDescriptor.java:359)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:189)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:78)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:132)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:220)
	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$6(DefaultLauncher.java:188)
	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:202)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:181)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:128)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:150)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)

2020-11-04 11:12:02,428 INFO  [net.ado.api.v3.dat.per.mon.MongoClient$Companion] (pool-3-thread-1) Using development connection string - mongodb://null:null/?serverSelectionTimeoutMS=null
2020-11-04 11:12:02,428 ERROR [net.ado.api.v3.dat.APIDataStore] (pool-3-thread-1) Failed to load db: java.lang.IllegalArgumentException: The connection string contains an invalid host 'null:null'. The port 'null' is not a valid, it must be an integer between 0 and 65535
<same ish stack dump>
```
6. cd into the `adoptopenjdk-api-v3-updater` dir and execute `java -jar ./target/adoptopenjdk-api-v3-updater-3.0.0-SNAPSHOT-jar-with-dependencies.jar` with the java binary mentioned above set to the JAVA_HOME.
7. See Error:
```
➜  adoptopenjdk-api-v3-updater git:(master) java -jar ./target/adoptopenjdk-api-v3-updater-3.0.0-SNAPSHOT-jar-with-dependencies.jar
2020-11-04 11:18:00,450 INFO [main] n.a.a.v.d.p.m.MongoClient$Companion [MongoClient.kt:51]
Using development connection string - mongodb://null:null/?serverSelectionTimeoutMS=null
Exception in thread "main" java.lang.IllegalArgumentException: The connection string contains an invalid host 'null:null'. The port 'null' is not a valid, it must be an integer between 0 and 65535
	at com.mongodb.ConnectionString.validatePort(ConnectionString.java:1003)
	at com.mongodb.ConnectionString.parseHosts(ConnectionString.java:983)
	at com.mongodb.ConnectionString.<init>(ConnectionString.java:340)
	at org.litote.kmongo.reactivestreams.KMongo.createClient(KMongo.kt:57)
	at net.adoptopenjdk.api.v3.dataSources.persitence.mongo.MongoClient.<init>(MongoClient.kt:68)
	at net.adoptopenjdk.api.v3.dataSources.persitence.mongo.MongoClientFactory.get(MongoClient.kt:15)
	at net.adoptopenjdk.api.v3.dataSources.ApiPersistenceFactory.get(ApiPersistenceFactory.kt:13)
	at net.adoptopenjdk.api.v3.V3Updater.<init>(V3Updater.kt:29)
	at net.adoptopenjdk.api.v3.V3Updater$Companion.main(V3Updater.kt:45)
	at net.adoptopenjdk.api.v3.V3Updater.main(V3Updater.kt)
```

**Expected behavior**
Artifact generator to complete without this error and the updater tool to run without failing with this error

**Device (please complete the following information):**
 - OS: MacOS Catalina, Version 10.15.6
 - Browser: Chrome 86.0.4240.80 (Official Build) (x86_64)
 - Version: I assume this means the repo? In which case, it's the same version as the current master branch (and is being executed on the master branch)

**Additional context**
When executing the updater tool, I noticed the log above it `Using development connection string - mongodb://null:null/?serverSelectionTimeoutMS=null` which leads to this companion object. I also saw this in the stack thread. Is the `DEFAULT_HOST` and `DEFAULT_PORT` actually getting passed to the `developmentConnectionString` when `MONGODB_HOST` / `MONGODB_PORT` are `null` (which they are in my case)? If the intended behaviour IS to fail should be not have the mongo env variables set however, we should probably document that you should have `MONGODB_HOST` and `MONGODB_PORT` set in order to replicate the API locally.
https://github.com/AdoptOpenJDK/openjdk-api-v3/blob/2f40f2db9258909e461543062502d1eacede2502/adoptopenjdk-api-v3-persistance/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/persitence/mongo/MongoClient.kt#L29-L70

**Comment by M-Davies** [comment]
When setting `MONGODB_HOST` to `localhost` and `MONGODB_PORT` to `27017`, I get this error in lieu of the other one `null:null` one above:
```
2020-11-04 11:58:55,946 ERROR [net.ado.api.v3.dat.APIDataStore] (main) Failed to read db: java.lang.IllegalArgumentException: The connection string contains an invalid value for 'serverselectiontimeoutms'. 'null' is not a valid integer
```

**Comment by nickebbitt** [comment]
good spot 👍 

while not a solution to your problem, an option for running locally is via [Docker](https://github.com/AdoptOpenJDK/openjdk-api-v3/blob/master/CONTRIBUTING.md#docker) which encapsulates the build and means you don't need to install mongo on your local host

the docker-compose.yaml file also takes care of the required environment set up for running locally: https://github.com/AdoptOpenJDK/openjdk-api-v3/blob/master/docker-compose.yml#L27

**Comment by M-Davies** [comment]
Fixed by https://github.com/AdoptOpenJDK/openjdk-api-v3/pull/299
