### ISSUE TITLE
NoClassDefFoundError on FrontEnd Build

### ISSUE THREAD

**Issue by M-Davies** [AdoptOpenJDK/openjdk-api-v3#302]
**Describe the bug**
When running `../mvnw quarkus:dev`, I encountered a `NoClassDefFoundError` when executing and also when viewing the API at localhost:8080. NOTE, this was all done outside a docker container, I haven't tried inside one yet.

**To Reproduce**
1. Let the API Updater run a full cycle with `mvnw clean install` and `java -jar ./target/adoptopenjdk-api-v3-updater-3.0.0-SNAPSHOT-jar-with-dependencies.jar`
2. cd into the frontend dir
3. Execute `../mvnw quarkus:dev`
4. See error in console log...
```
2020-11-09 08:36:23,879 ERROR [io.qua.run.boo.StartupActionImpl] (Quarkus Main Thread) Error running Quarkus: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.runner.bootstrap.StartupActionImpl$3.run(StartupActionImpl.java:145)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ExceptionInInitializerError
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/java.lang.Class.newInstance(Class.java:584)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:60)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:38)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:106)
	at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:29)
	... 6 more
Caused by: java.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.runner.ApplicationImpl.<clinit>(ApplicationImpl.zig:230)
	... 15 more
Caused by: java.lang.NoClassDefFoundError: net/adoptopenjdk/api/v3/dataSources/APIDataStore
	at net.adoptopenjdk.api.v3.V3.schedulePeriodicUpdates(V3.kt:83)
	at net.adoptopenjdk.api.v3.V3.<init>(V3.kt:62)
	at net.adoptopenjdk.api.v3.V3_Bean.create(V3_Bean.zig:139)
	at net.adoptopenjdk.api.v3.V3_Bean.create(V3_Bean.zig:154)
	at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:88)
	at io.quarkus.arc.impl.ComputingCache$CacheFunction.lambda$apply$0(ComputingCache.java:99)
	at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:26)
	at io.quarkus.arc.impl.ComputingCache.getValue(ComputingCache.java:41)
	at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:25)
	at net.adoptopenjdk.api.v3.V3_Bean.get(V3_Bean.zig:186)
	at net.adoptopenjdk.api.v3.V3_Bean.get(V3_Bean.zig:202)
	at io.quarkus.arc.impl.ArcContainerImpl.beanInstanceHandle(ArcContainerImpl.java:408)
	at io.quarkus.arc.impl.ArcContainerImpl.beanInstanceHandle(ArcContainerImpl.java:421)
	at io.quarkus.arc.impl.ArcContainerImpl$1.get(ArcContainerImpl.java:249)
	at io.quarkus.arc.impl.ArcContainerImpl$1.get(ArcContainerImpl.java:246)
	at io.quarkus.arc.runtime.ArcRecorder$2$1.create(ArcRecorder.java:84)
	at io.quarkus.resteasy.common.runtime.QuarkusConstructorInjector.construct(QuarkusConstructorInjector.java:39)
	at org.jboss.resteasy.core.providerfactory.Utils.createProviderInstance(Utils.java:102)
	at org.jboss.resteasy.core.providerfactory.ResteasyProviderFactoryImpl.createProviderInstance(ResteasyProviderFactoryImpl.java:1384)
	at org.jboss.resteasy.core.ResteasyDeploymentImpl.createApplication(ResteasyDeploymentImpl.java:415)
	at org.jboss.resteasy.core.ResteasyDeploymentImpl.initializeObjects(ResteasyDeploymentImpl.java:262)
	at org.jboss.resteasy.core.ResteasyDeploymentImpl.startInternal(ResteasyDeploymentImpl.java:135)
	at org.jboss.resteasy.core.ResteasyDeploymentImpl.start(ResteasyDeploymentImpl.java:118)
	at io.quarkus.resteasy.runtime.standalone.ResteasyStandaloneRecorder.staticInit(ResteasyStandaloneRecorder.java:86)
	at io.quarkus.deployment.steps.ResteasyStandaloneBuildStep$staticInit-210558872.deploy_0(ResteasyStandaloneBuildStep$staticInit-210558872.zig:1165)
	at io.quarkus.deployment.steps.ResteasyStandaloneBuildStep$staticInit-210558872.deploy(ResteasyStandaloneBuildStep$staticInit-210558872.zig:36)
	at io.quarkus.runner.ApplicationImpl.<clinit>(ApplicationImpl.zig:213)
	... 15 more
Caused by: java.lang.ClassNotFoundException: net.adoptopenjdk.api.v3.dataSources.APIDataStore
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:396)
	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:333)
	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:396)
	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:333)
	... 42 more
```
and on localhost:8080...
<img width="1440" alt="Screenshot 2020-11-09 at 08 45 17" src="https://user-images.githubusercontent.com/25231953/98518908-f4dc8280-2267-11eb-9b27-91506a5d9b02.png">

**Expected behavior**
Frontend build to run without errors and localhost:8080 display the frontend of the API

**Device (please complete the following information):**
- OS: MacOS Catalina, Version 10.15.6
- Browser: Chrome 86.0.4240.80 (Official Build) (x86_64)
- Version: I assume this means the repo? In which case, it's the same version as the current master branch (and is being executed on the master branch)

**Comment by karianna** [comment]
This has been fixed.

**Comment by M-Davies** [comment]
> This has been fixed.

@karianna Can you explain how? Not doubting, just curious as there hasn't been anything posted that I have seen

**Comment by karianna** [comment]
> > This has been fixed.
> 
> @karianna Can you explain how? Not doubting, just curious as there hasn't been anything posted that I have seen

Ran this locally with updated deps and the issue had gone.
