### ISSUE TITLE
API seems very unstable over the last few days

### ISSUE THREAD

**Issue by sxa** [AdoptOpenJDK/openjdk-api-v3#341]
**Describe the bug**
Lots of messages being posted to the #general channel on slack since Wednesday about the API (both V2 and V3) going down - also visible on https://status.adoptopenjdk.net/

Some builds have had problems pulling from the API over the last few days as well.

Logs are showing instances of `javax.ws.rs.BadRequestException: Unable to parse version` and this:
```
Remaining data getting low (999, 0) 1 10
2021-01-10 12:51:32,646 INFO [DefaultDispatcher-worker-1] n.a.a.v.d.DefaultUpdaterHtmlClient$Companion [UpdaterHtmlClient.kt:135]
Getting https://api.github.com/rate_limit  null
```
which I assume aren't normal

**Comment by andrew-m-leonard** [comment]
Extra debug information here would be useful, to know what the parse version error is?
https://github.com/AdoptOpenJDK/openjdk-api-v3/blob/f996b3086ae74346834efda25f169f5c83498721/adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/VersionResource.kt#L42

**Comment by aahlenst** [comment]
> Extra debug information here would be useful, to know what the parse version error is?

Not present in the logs. Would need better debug info. Anyhow, failures there shouldn't make the API unstable.

**Comment by andrew-m-leonard** [comment]
Instances from weekend:
https://ci.adoptopenjdk.net/view/Failing%20Test%20Jobs/job/Test_openjdk11_j9_extended.external_ppc64le_linux_scala/24/console

**Comment by andrew-m-leonard** [comment]
What maybe useful is when the failure occurs here:
```
14:05:54  get jdk binary...
14:05:54  _ENCODE_FILE_NEW=UNTAGGED curl -OLJSks  https://api.adoptopenjdk.net/v3/binary/latest/11/ea/linux/ppc64le/jdk/openj9/normal/adoptopenjdk
14:06:05  _ENCODE_FILE_NEW=UNTAGGED curl -OLJSks  https://api.adoptopenjdk.net/v3/binary/latest/11/ea/linux/ppc64le/testimage/openj9/normal/adoptopenjdk
14:06:05  unzip file: adoptopenjdk ...
14:06:05  
14:06:05  gzip: adoptopenjdk: not in gzip format
14:06:05  tar: This does not look like a tar archive
14:06:05  tar: Exiting with failure status due to previous errors
```
It's possible the content is html error/readable test, if so adding some debug here to echo content if it's not large

**Comment by adamfarley** [comment]
Looking into it.

**Comment by nickebbitt** [comment]
what action(s) do we perform to health check the API to determine an outage or not? as respresented by those alerts triggering and via https://status.adoptopenjdk.net/

**Comment by sxa** [comment]
If nothing else it's probably worth
- checking if we're verifying the return code of the curl operation since we seem to be falling over on a subsequent decompress of a corrupt file here
- Removing `-s` from the curl command so we can see the output from it

**Comment by sxa** [comment]
> So it makes sense that "adoptopenjdk" isn't a build, fragmented, corrupted, or whole. Looking into a "plain text check" for the code.

That definitely feels a bit more like an API issue than a github issue to me ...

**Comment by adamfarley** [comment]
We do check the return code from the curl. It passes. So the download is successful, we're just not getting what we asked for.

**Comment by adamfarley** [comment]
```
_ENCODE_FILE_NEW=UNTAGGED curl -OLJSk${curl_verbosity} ${curl_options} $file
				download_exit_code=$?
				count=$(( $count + 1 ))
			done

			if [ $download_exit_code != 0 ]; then
				echo "curl error code: $download_exit_code"
```

**Comment by karianna** [comment]
```
AI: ERROR 08-01-2021 17:00:39.423+0000, 50(ActiveTransmissionNetworkOutput_1-5): Failed to send.
Stack Trace:
java.net.SocketTimeoutException: Read timed out
	at java.base/java.net.SocketInputStream.socketRead0(Native Method)
	at java.base/java.net.SocketInputStream.socketRead(SocketInputStream.java:115)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:168)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:140)
	at java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:467)
	at java.base/sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:461)
	at java.base/sun.security.ssl.SSLSocketInputRecord.bytesInCompletePacket(SSLSocketInputRecord.java:70)
	at java.base/sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1349)
	at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:958)
	at com.microsoft.applicationinsights.core.dependencies.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137)
	at com.microsoft.applicationinsights.core.dependencies.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:153)
	at com.microsoft.applicationinsights.core.dependencies.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:282)
	at com.microsoft.applicationinsights.core.dependencies.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:138)
	at com.microsoft.applicationinsights.core.dependencies.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:56)
	at com.microsoft.applicationinsights.core.dependencies.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259)
	at com.microsoft.applicationinsights.core.dependencies.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:163)
	at com.microsoft.applicationinsights.core.dependencies.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:165)
	at com.microsoft.applicationinsights.core.dependencies.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273)
	at com.microsoft.applicationinsights.core.dependencies.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125)
	at com.microsoft.applicationinsights.core.dependencies.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272)
	at com.microsoft.applicationinsights.core.dependencies.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
	at com.microsoft.applicationinsights.core.dependencies.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at com.microsoft.applicationinsights.core.dependencies.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111)
	at com.microsoft.applicationinsights.core.dependencies.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at com.microsoft.applicationinsights.core.dependencies.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at com.microsoft.applicationinsights.core.dependencies.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
	at com.microsoft.applicationinsights.core.dependencies.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
	at com.microsoft.applicationinsights.internal.channel.common.ApacheSender43.sendPostRequest(ApacheSender43.java:82)
	at com.microsoft.applicationinsights.internal.channel.common.TransmissionNetworkOutput.send(TransmissionNetworkOutput.java:176)
	at com.microsoft.applicationinsights.internal.channel.common.ActiveTransmissionNetworkOutput$1.run(ActiveTransmissionNetworkOutput.java:79)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by karianna** [comment]
```
2021-01-07 13:15:27,402 ERROR [org.jbo.res.res.i18n] (executor-thread-14219) RESTEASY002010: Failed to execute: javax.ws.rs.BadRequestException: Cannot parse date
	at net.adoptopenjdk.api.v3.routes.AssetsResource.parseDate(AssetsResource.kt:194)
	at net.adoptopenjdk.api.v3.routes.AssetsResource.get(AssetsResource.kt:146)
	at net.adoptopenjdk.api.v3.routes.AssetsResource_Subclass.get$$superaccessor1(AssetsResource_Subclass.zig:508)
	at net.adoptopenjdk.api.v3.routes.AssetsResource_Subclass$$function$$1.apply(AssetsResource_Subclass$$function$$1.zig:113)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
	at io.smallrye.metrics.interceptors.TimedInterceptor.timedCallable(TimedInterceptor.java:95)
	at io.smallrye.metrics.interceptors.TimedInterceptor.timedMethod(TimedInterceptor.java:70)
	at io.smallrye.metrics.interceptors.TimedInterceptor_Bean.intercept(TimedInterceptor_Bean.zig:366)
	at io.quarkus.arc.impl.InitializedInterceptor.intercept(InitializedInterceptor.java:79)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
	at net.adoptopenjdk.api.v3.routes.AssetsResource_Subclass.get(AssetsResource_Subclass.zig:439)
	at jdk.internal.reflect.GeneratedMethodAccessor56.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:167)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
	at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:638)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:504)
	at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:454)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:456)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:417)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:391)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:68)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:488)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:259)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:160)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:163)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:245)
	at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:132)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.access$000(VertxRequestHandler.java:37)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler$1.run(VertxRequestHandler.java:94)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2046)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1578)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at java.base/java.lang.Thread.run(Thread.java:834)
	at org.jboss.threads.JBossThread.run(JBossThread.java:479)
```

**Comment by karianna** [comment]
The last time binaries were imported was on Saturday.

```
2021-01-09 09:52:10,696 INFO  [net.ado.api.v3.dat.APIDataStore] (pool-1-thread-1) Loaded Version: 2021-01-09T09:51:21Z 5aDK4kUSS+e/miQ2OPYhcA==
2021-01-09 09:52:10,711 INFO  [net.ado.api.v3.dat.APIDataStore] (pool-1-thread-1) New release: jdk16-2021-01-09-06-41 2
2021-01-09 09:52:10,711 INFO  [net.ado.api.v3.dat.APIDataStore] (pool-1-thread-1) New release: jdk16-2021-01-09-06-41 53
AI: INFO 09-01-2021 10:51:44.848+0000, 15500(executor-thread-15202): Total events generated till now 2900000
AI: INFO 09-01-2021 10:51:44.848+0000, 15500(executor-thread-15202): items sent till now 2900000
2021-01-09 14:08:16,088 INFO  [net.ado.api.v3.dat.APIDataStore] (pool-1-thread-1) Loaded Version: 2021-01-09T14:07:56Z vXnq6KV/aYPIXU2iUC6xNg==
2021-01-09 14:08:16,103 INFO  [net.ado.api.v3.dat.APIDataStore] (pool-1-thread-1) New release: jdk8u-2021-01-09-09-26 0
2021-01-09 14:08:16,103 INFO  [net.ado.api.v3.dat.APIDataStore] (pool-1-thread-1) New release: jdk8u-2021-01-09-09-26 2
2021-01-09 14:08:16,103 INFO  [net.ado.api.v3.dat.APIDataStore] (pool-1-thread-1) New release: jdk8u-2021-01-09-09-26 2
2021-01-09 14:08:16,103 INFO  [net.ado.api.v3.dat.APIDataStore] (pool-1-thread-1) New release: jdk8u-2021-01-09-09-26 70
2021-01-09 14:08:16,104 INFO  [net.ado.api.v3.dat.APIDataStore] (pool-1-thread-1) Binary count changed jdk16-2021-01-09-06-41 2 -> 3
2021-01-09 14:08:16,104 INFO  [net.ado.api.v3.dat.APIDataStore] (pool-1-thread-1) Binary count changed jdk16-2021-01-09-06-41 53 -> 78
````

**Comment by johnoliver** [comment]
> ```
> AI: ERROR 08-01-2021 17:00:39.423+0000, 50(ActiveTransmissionNetworkOutput_1-5): Failed to send.
> Stack Trace:
> java.net.SocketTimeoutException: Read timed out
> 	at java.base/java.net.SocketInputStream.socketRead0(Native Method)
> 	at java.base/java.net.SocketInputStream.socketRead(SocketInputStream.java:115)
> 	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:168)
> 	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:140)
> 	at java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:467)
> 	at java.base/sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:461)
> 	at java.base/sun.security.ssl.SSLSocketInputRecord.bytesInCompletePacket(SSLSocketInputRecord.java:70)
> 	at java.base/sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1349)
> 	at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:958)
> 	at com.microsoft.applicationinsights.core.dependencies.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137)
> 	at com.microsoft.applicationinsights.core.dependencies.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:153)
> 	at com.microsoft.applicationinsights.core.dependencies.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:282)
> 	at com.microsoft.applicationinsights.core.dependencies.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:138)
> 	at com.microsoft.applicationinsights.core.dependencies.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:56)
> 	at com.microsoft.applicationinsights.core.dependencies.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259)
> 	at com.microsoft.applicationinsights.core.dependencies.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:163)
> 	at com.microsoft.applicationinsights.core.dependencies.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:165)
> 	at com.microsoft.applicationinsights.core.dependencies.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273)
> 	at com.microsoft.applicationinsights.core.dependencies.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125)
> 	at com.microsoft.applicationinsights.core.dependencies.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272)
> 	at com.microsoft.applicationinsights.core.dependencies.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
> 	at com.microsoft.applicationinsights.core.dependencies.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
> 	at com.microsoft.applicationinsights.core.dependencies.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111)
> 	at com.microsoft.applicationinsights.core.dependencies.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
> 	at com.microsoft.applicationinsights.core.dependencies.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
> 	at com.microsoft.applicationinsights.core.dependencies.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
> 	at com.microsoft.applicationinsights.core.dependencies.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
> 	at com.microsoft.applicationinsights.internal.channel.common.ApacheSender43.sendPostRequest(ApacheSender43.java:82)
> 	at com.microsoft.applicationinsights.internal.channel.common.TransmissionNetworkOutput.send(TransmissionNetworkOutput.java:176)
> 	at com.microsoft.applicationinsights.internal.channel.common.ActiveTransmissionNetworkOutput$1.run(ActiveTransmissionNetworkOutput.java:79)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
> 	at java.base/java.lang.Thread.run(Thread.java:834)
> ```

This is just an error communication to ApplicationInsights and not an issue

**Comment by karianna** [comment]
Downtime started by 525 (invalid SSL Handshake) and then subsequent 520's.  We can't see anything specific to have caused this. Could just have been an SSL cert refresh managed by Cloudflare that didn't go smoothly. 

We will leave this open for a few more days JIC more info comes to light, else we'll close it.

**Comment by adamfarley** [comment]
Have created a debug copy of openjdk-tests where the relevant script fetches the file repeatedly. If we get an "adoptopenjdk" file, we try to print the contents.

Note that only the second bit will go in, if this gets approved and merged eventually.

**Comment by adamfarley** [comment]
Ok, the code worked. Over several hundred runs, we see several of these:

```
13:03:51  <html>
13:03:51  <head>
13:03:51  <meta name="viewport" content="width=device-width, initial-scale=1">

...Removed one big ol' style tag...

13:03:51  </head>
13:03:51  <body>
13:03:51  <div>
13:03:51  <h1>Application is not available</h1>
13:03:51  <p>The application is currently not serving requests at this endpoint. It may not have been started or is still starting.</p>
13:03:51  <div class="alert alert-info">
13:03:51  <p class="info">
13:03:51  Possible reasons you are seeing this page:
13:03:51  </p>
13:03:51  <ul>
13:03:51  <li>
13:03:51  <strong>The host doesn't exist.</strong>
13:03:51  Make sure the hostname was typed correctly and that a route matching this hostname exists.
13:03:51  </li>
13:03:51  <li>
13:03:51  <strong>The host exists, but doesn't have a matching path.</strong>
13:03:51  Check if the URL path was typed correctly and that the route was created using the desired path.
13:03:51  </li>
13:03:51  <li>
13:03:51  <strong>Route and path matches, but all pods are down.</strong>
13:03:51  Make sure that the resources exposed by this route (pods, services, deployment configs, etc) have at least one pod running.
13:03:51  </li>
13:03:51  </ul>
13:03:51  </div>
13:03:51  </div>
13:03:51  </body>
13:03:51  </html>
```

**Comment by adamfarley** [comment]
Since we're supposed to retry "failed" downloads 5 times, it seems right to me that we trigger the "retry" functionality on the presence of this file, but only if we're using the api. Will put some code together.

**Comment by andrew-m-leonard** [comment]
https://bobcares.com/blog/tips-to-fix-cloudflare-520-error/

**Comment by sxa** [comment]
If we have a 3% error rate on the API I think we have an underlying problem to work on which we shoulkdn't just "work around and forget about" as this will be affecting our consumers and that's not a good failure rate

**Comment by adamfarley** [comment]
Currently, we have a retry functionality that identifies when the curl command has failed and retries 5 times with 5 minute gaps.

Is there a distinction between "the curl command knows it has failed" and " the curl command does not know, but the api does"?

**Comment by adamfarley** [comment]
Also, here's a PR if we decide to do a workaround: https://github.com/AdoptOpenJDK/openjdk-tests/pull/2153

**Comment by adamfarley** [comment]
Also, does anyone have the api server/cloudflare access to try the things suggested in Andrew's link?

**Comment by sxa** [comment]
> Is there a distinction between "the curl command knows it has failed" and " the curl command does not know, but the api does"?

Which HTTP status code is it returning in the case of the `Application is not available` message? I'd hope we can trap that assuming it's something meaningful

**Comment by adamfarley** [comment]
Getting the http code now. May take a few minutes for the grinder to run.

**Comment by sxa** [comment]
`-D` will write the headers to another location. I did a quick loop:
```
touch output
while grep 200.OK output; do date;  curl -OLD output https://api.adoptopenjdk.net/v3/binary/latest/8/ga/aix/ppc64/jre/hotspot/normal/adoptopenjdk?project=jdk; done
```
It stopped once it got this set of headers:
```
HTTP/1.1 503 Service Unavailable
Date: Mon, 11 Jan 2021 16:55:38 GMT
Content-Type: text/html
Transfer-Encoding: chunked
Connection: keep-alive
Set-Cookie: __cfduid=dcd33163b1ebead418153f51d739548ca1610384138; expires=Wed, 10-Feb-21 16:55:38 GMT; path=/; domain=.adoptopenjdk.net; HttpOnly; SameSite=Lax
Pragma: no-cache
Cache-Control: private, max-age=0, no-cache, no-store
CF-Cache-Status: DYNAMIC
cf-request-id: 0793f8f7c50000bee2401c4000000001
Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
Server: cloudflare
CF-RAY: 61002a9f9b4dbee2-FRA
```

**Comment by adamfarley** [comment]
So, it looks like we're getting three sorts of HTTP return codes between 1% and 4% of the time:

- 503 Service Unavailable
- (unknown code, possibly 503) Application is not available
- 520 Origin Error

Since all three are coming out of Cloudflare, one option is to go through the following URL and try some of the proposed steps.
https://bobcares.com/blog/tips-to-fix-cloudflare-520-error/
It's also worth consulting whether something's chewing up cpu time or available memory on the api server. 

Raising an infrastructure issue to address these. 

Also, while we're at it, it's worth consulting system/api webserver logs to see if any errors were reported when Stewart saw his 503 code above:

```
HTTP/1.1 503 Service Unavailable
Date: Mon, 11 Jan 2021 16:55:38 GMT
```

**Comment by karianna** [comment]
This has since been resolved by Cloudflare upstream.
